npmRegistryServer: "http://192.168.0.49:8085/repository/registry.npmjs.org/"
npmScopes:
  "bsky":
    npmRegistryServer: "http://192.168.0.49:8085/repository/registry.npmjs.org/"
unsafeHttpWhitelist:
  - "192.168.0.49"
