project_id: '1'
base_url: 'https://bluesky.api.crowdin.com'
base_path: .
preserve_hierarchy: 1
files:
  - source: /src/locale/locales/en/messages.po
    translation: /src/locale/locales/%two_letters_code%/messages.po
    languages_mapping:
      two_letters_code:
        pt-BR: pt-BR
        en-GB: en-GB
        zh-CN: zh-CN
        zh-TW: zh-TW
        zh-HK: zh-HK
